# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: aion.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'aion.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\naion.proto\x12\x0e\x61ion.execution\"C\n\x0bTaskRequest\x12\x13\n\x0b\x65xternal_id\x18\x01 \x01(\t\x12\x0e\n\x06intent\x18\x02 \x01(\t\x12\x0f\n\x07payload\x18\x03 \x01(\t\"C\n\x0cTaskResponse\x12\x13\n\x0b\x65xternal_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x0e\n\x06output\x18\x03 \x01(\t2X\n\x0cTaskExecutor\x12H\n\x0b\x45xecuteTask\x12\x1b.aion.execution.TaskRequest\x1a\x1c.aion.execution.TaskResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aion_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TASKREQUEST']._serialized_start=30
  _globals['_TASKREQUEST']._serialized_end=97
  _globals['_TASKRESPONSE']._serialized_start=99
  _globals['_TASKRESPONSE']._serialized_end=166
  _globals['_TASKEXECUTOR']._serialized_start=168
  _globals['_TASKEXECUTOR']._serialized_end=256
# @@protoc_insertion_point(module_scope)
