# Generated by hand for simplified proto definitions.
from __future__ import annotations

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

_sym_db = _symbol_database.Default()

DESCRIPTOR = _descriptor.FileDescriptor(
  name='execution.proto',
  package='aion.execution',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b"\n\x0fexecution.proto\x12\x0eaion.execution\"<\n\x0bTaskRequest\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12\x0e\n\x06intent\x18\x02 \x01(\t\x12\x14\n\x0cpayload_json\x18\x03 \x01(\t\"4\n\tTaskReply\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x13\n\x0bresult_json\x18\x02 \x01(\t2U\n\nTaskModule\x12G\n\x07Execute\x12\x1b.aion.execution.TaskRequest\x1a\x19.aion.execution.TaskReply\"\x00\x62\x06proto3"
)


_TASKREQUEST = _descriptor.Descriptor(
  name='TaskRequest',
  full_name='aion.execution.TaskRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='task_id', full_name='aion.execution.TaskRequest.task_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='intent', full_name='aion.execution.TaskRequest.intent', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='payload_json', full_name='aion.execution.TaskRequest.payload_json', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[],
  nested_types=[],
  enum_types=[],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[],
  serialized_start=33,
  serialized_end=93,
)

_TASKREPLY = _descriptor.Descriptor(
  name='TaskReply',
  full_name='aion.execution.TaskReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='aion.execution.TaskReply.status', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='result_json', full_name='aion.execution.TaskReply.result_json', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[],
  nested_types=[],
  enum_types=[],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[],
  serialized_start=95,
  serialized_end=147,
)

DESCRIPTOR.message_types_by_name['TaskRequest'] = _TASKREQUEST
DESCRIPTOR.message_types_by_name['TaskReply'] = _TASKREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TaskRequest = _reflection.GeneratedProtocolMessageType('TaskRequest', (_message.Message,), {
  'DESCRIPTOR' : _TASKREQUEST,
  '__module__' : 'execution_pb2'
})
_sym_db.RegisterMessage(TaskRequest)

TaskReply = _reflection.GeneratedProtocolMessageType('TaskReply', (_message.Message,), {
  'DESCRIPTOR' : _TASKREPLY,
  '__module__' : 'execution_pb2'
})
_sym_db.RegisterMessage(TaskReply)

_TASKMODULE = _descriptor.ServiceDescriptor(
  name='TaskModule',
  full_name='aion.execution.TaskModule',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=149,
  serialized_end=234,
  methods=[
  _descriptor.MethodDescriptor(
    name='Execute',
    full_name='aion.execution.TaskModule.Execute',
    index=0,
    containing_service=None,
    input_type=_TASKREQUEST,
    output_type=_TASKREPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_TASKMODULE)

TaskModule = _TASKMODULE

