global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'gateway'
    static_configs:
      - targets: ['gateway:8080']
  - job_name: 'control'
    metrics_path: /metrics
    static_configs:
      - targets: ['control:8000']
