# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from aion.v1 import tasks_pb2 as aion_dot_v1_dot_tasks__pb2


class AionTasksStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Submit = channel.unary_unary(
                '/aion.v1.AionTasks/Submit',
                request_serializer=aion_dot_v1_dot_tasks__pb2.TaskRequest.SerializeToString,
                response_deserializer=aion_dot_v1_dot_tasks__pb2.TaskResult.FromString,
                )
        self.Stream = channel.unary_stream(
                '/aion.v1.AionTasks/Stream',
                request_serializer=aion_dot_v1_dot_tasks__pb2.TaskRequest.SerializeToString,
                response_deserializer=aion_dot_v1_dot_tasks__pb2.StreamChunk.FromString,
                )
        self.AckStream = channel.unary_unary(
                '/aion.v1.AionTasks/AckStream',
                request_serializer=aion_dot_v1_dot_tasks__pb2.StreamAck.SerializeToString,
                response_deserializer=aion_dot_v1_dot_tasks__pb2.AckResponse.FromString,
                )
        self.StatusById = channel.unary_unary(
                '/aion.v1.AionTasks/StatusById',
                request_serializer=aion_dot_v1_dot_tasks__pb2.TaskId.SerializeToString,
                response_deserializer=aion_dot_v1_dot_tasks__pb2.TaskResult.FromString,
                )


class AionTasksServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Submit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Stream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AckStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StatusById(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AionTasksServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Submit': grpc.unary_unary_rpc_method_handler(
                    servicer.Submit,
                    request_deserializer=aion_dot_v1_dot_tasks__pb2.TaskRequest.FromString,
                    response_serializer=aion_dot_v1_dot_tasks__pb2.TaskResult.SerializeToString,
            ),
            'Stream': grpc.unary_stream_rpc_method_handler(
                    servicer.Stream,
                    request_deserializer=aion_dot_v1_dot_tasks__pb2.TaskRequest.FromString,
                    response_serializer=aion_dot_v1_dot_tasks__pb2.StreamChunk.SerializeToString,
            ),
            'AckStream': grpc.unary_unary_rpc_method_handler(
                    servicer.AckStream,
                    request_deserializer=aion_dot_v1_dot_tasks__pb2.StreamAck.FromString,
                    response_serializer=aion_dot_v1_dot_tasks__pb2.AckResponse.SerializeToString,
            ),
            'StatusById': grpc.unary_unary_rpc_method_handler(
                    servicer.StatusById,
                    request_deserializer=aion_dot_v1_dot_tasks__pb2.TaskId.FromString,
                    response_serializer=aion_dot_v1_dot_tasks__pb2.TaskResult.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'aion.v1.AionTasks', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AionTasks(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Submit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/aion.v1.AionTasks/Submit',
            aion_dot_v1_dot_tasks__pb2.TaskRequest.SerializeToString,
            aion_dot_v1_dot_tasks__pb2.TaskResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Stream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/aion.v1.AionTasks/Stream',
            aion_dot_v1_dot_tasks__pb2.TaskRequest.SerializeToString,
            aion_dot_v1_dot_tasks__pb2.StreamChunk.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AckStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/aion.v1.AionTasks/AckStream',
            aion_dot_v1_dot_tasks__pb2.StreamAck.SerializeToString,
            aion_dot_v1_dot_tasks__pb2.AckResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StatusById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/aion.v1.AionTasks/StatusById',
            aion_dot_v1_dot_tasks__pb2.TaskId.SerializeToString,
            aion_dot_v1_dot_tasks__pb2.TaskResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
