# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from aion.v1 import tasks_pb2 as aion_dot_v1_dot_tasks__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in aion/v1/tasks_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AionTasksStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Submit = channel.unary_unary(
                '/aion.v1.AionTasks/Submit',
                request_serializer=aion_dot_v1_dot_tasks__pb2.TaskRequest.SerializeToString,
                response_deserializer=aion_dot_v1_dot_tasks__pb2.TaskResult.FromString,
                _registered_method=True)
        self.Stream = channel.unary_stream(
                '/aion.v1.AionTasks/Stream',
                request_serializer=aion_dot_v1_dot_tasks__pb2.TaskRequest.SerializeToString,
                response_deserializer=aion_dot_v1_dot_tasks__pb2.TaskResult.FromString,
                _registered_method=True)
        self.StatusById = channel.unary_unary(
                '/aion.v1.AionTasks/StatusById',
                request_serializer=aion_dot_v1_dot_tasks__pb2.TaskId.SerializeToString,
                response_deserializer=aion_dot_v1_dot_tasks__pb2.TaskResult.FromString,
                _registered_method=True)


class AionTasksServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Submit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Stream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StatusById(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AionTasksServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Submit': grpc.unary_unary_rpc_method_handler(
                    servicer.Submit,
                    request_deserializer=aion_dot_v1_dot_tasks__pb2.TaskRequest.FromString,
                    response_serializer=aion_dot_v1_dot_tasks__pb2.TaskResult.SerializeToString,
            ),
            'Stream': grpc.unary_stream_rpc_method_handler(
                    servicer.Stream,
                    request_deserializer=aion_dot_v1_dot_tasks__pb2.TaskRequest.FromString,
                    response_serializer=aion_dot_v1_dot_tasks__pb2.TaskResult.SerializeToString,
            ),
            'StatusById': grpc.unary_unary_rpc_method_handler(
                    servicer.StatusById,
                    request_deserializer=aion_dot_v1_dot_tasks__pb2.TaskId.FromString,
                    response_serializer=aion_dot_v1_dot_tasks__pb2.TaskResult.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'aion.v1.AionTasks', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('aion.v1.AionTasks', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AionTasks(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Submit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aion.v1.AionTasks/Submit',
            aion_dot_v1_dot_tasks__pb2.TaskRequest.SerializeToString,
            aion_dot_v1_dot_tasks__pb2.TaskResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Stream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/aion.v1.AionTasks/Stream',
            aion_dot_v1_dot_tasks__pb2.TaskRequest.SerializeToString,
            aion_dot_v1_dot_tasks__pb2.TaskResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StatusById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aion.v1.AionTasks/StatusById',
            aion_dot_v1_dot_tasks__pb2.TaskId.SerializeToString,
            aion_dot_v1_dot_tasks__pb2.TaskResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
