#!/usr/bin/env python3
"""Cross-platform preflight checks for OMERTAOS."""
from __future__ import annotations

import argparse
import json
import socket
import subprocess
import sys
from pathlib import Path
from typing import Dict, List, Tuple

REQUIRED_PORTS: Tuple[int, ...] = (3000, 8080, 8000, 50051, 5432, 6379, 6333, 9000, 9001, 11434)
REQUIRED_EXECUTABLES: Tuple[str, ...] = (
    "docker",
    "node",
    "python",
    "pip",
    "git",
)
OPTIONAL_EXECUTABLES: Tuple[str, ...] = ("ollama",)

ROOT = Path(__file__).resolve().parents[1]
ENV_FILE = ROOT / ".env"
ENV_SCHEMA = ROOT / ".env.schema"
ENV_EXAMPLE = ROOT / ".env.example"
CONFIG_DIR = ROOT / "config"
DEFAULT_CONFIG_FILE = CONFIG_DIR / "aionos.config.yaml"


class PreflightError(Exception):
    pass


def load_schema() -> Dict[str, Dict[str, str]]:
    if not ENV_SCHEMA.exists():
        raise PreflightError(f"Schema file missing: {ENV_SCHEMA}")
    try:
        payload = json.loads(ENV_SCHEMA.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        raise PreflightError(f"Failed to parse schema: {exc}") from exc
    variables = payload.get("variables")
    if not isinstance(variables, list):
        raise PreflightError("Schema 'variables' must be a list")
    mapping: Dict[str, Dict[str, str]] = {}
    for item in variables:
        if not isinstance(item, dict) or "name" not in item:
            raise PreflightError("Each variable entry must contain a name")
        mapping[item["name"]] = item
    return mapping


def ensure_env_file(schema: Dict[str, Dict[str, str]]) -> None:
    if not ENV_FILE.exists():
        if ENV_EXAMPLE.exists():
            ENV_FILE.write_text(ENV_EXAMPLE.read_text(encoding="utf-8"), encoding="utf-8")
        else:
            ENV_FILE.write_text("", encoding="utf-8")

    lines = ENV_FILE.read_text(encoding="utf-8").splitlines()
    existing: Dict[str, str] = {}
    for line in lines:
        striped = line.strip()
        if not striped or striped.startswith("#"):
            continue
        if "=" in line:
            key, value = line.split("=", 1)
            existing[key.strip()] = value

    appended: List[str] = []
    for name, spec in schema.items():
        if name not in existing:
            default = spec.get("default", "")
            appended.append(f"{name}={default}")
            existing[name] = default
    if appended:
        with ENV_FILE.open("a", encoding="utf-8") as handle:
            handle.write("\n" + "\n".join(appended) + "\n")

    missing_required = [name for name, spec in schema.items() if spec.get("required") and not existing.get(name)]
    if missing_required:
        raise PreflightError(f"Missing required variables in .env: {', '.join(missing_required)}")


def check_ports() -> None:
    failed: List[int] = []
    for port in REQUIRED_PORTS:
        sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        try:
            sock.bind(("127.0.0.1", port))
        except OSError:
            failed.append(port)
        finally:
            sock.close()
    if failed:
        raise PreflightError("Ports already in use: " + ", ".join(str(p) for p in failed))


def which(cmd: str) -> bool:
    from shutil import which as shutil_which

    return shutil_which(cmd) is not None


def check_executables() -> None:
    missing = [cmd for cmd in REQUIRED_EXECUTABLES if not which(cmd)]
    if missing:
        raise PreflightError("Missing executables: " + ", ".join(missing))
    missing_optional = [cmd for cmd in OPTIONAL_EXECUTABLES if not which(cmd)]
    if missing_optional:
        print(
            "Optional executables missing: " + ", ".join(missing_optional),
            file=sys.stderr,
        )
    # docker compose check
    try:
        subprocess.run(["docker", "compose", "version"], check=True, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    except (subprocess.CalledProcessError, FileNotFoundError) as exc:
        raise PreflightError("Docker Compose is not available (docker compose version failed)") from exc


def ensure_config() -> None:
    CONFIG_DIR.mkdir(parents=True, exist_ok=True)
    if not DEFAULT_CONFIG_FILE.exists():
        DEFAULT_CONFIG_FILE.write_text(
            """# Generated by tools/preflight.py\n# Runtime defaults for OMERTAOS\ntelemetry:\n  enabled: false\n  exporter: otlp\n  endpoint: http://localhost:4317\nrouter:\n  default_policy: standard\n""",
            encoding="utf-8",
        )


def run_checks(noninteractive: bool = False) -> None:
    schema = load_schema()
    ensure_env_file(schema)
    ensure_config()
    check_ports()
    check_executables()
    if not noninteractive:
        print("Preflight checks completed successfully.")


def main(argv: List[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Run OMERTAOS preflight checks")
    parser.add_argument("--noninteractive", action="store_true", help="Suppress success output")
    args = parser.parse_args(argv)
    try:
        run_checks(noninteractive=args.noninteractive)
    except PreflightError as exc:
        print(f"Preflight failed: {exc}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
