name: ASCII Lint
on:
  pull_request:
  push:
    branches: [ main, AIONOS, develop ]
jobs:
  ascii:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - uses: actions/setup-python@v5
        with: { python-version: '3.x' }
      - name: Run ASCII sanitizer
        run: python tools/sanitize_ascii.py
